# fly.toml app configuration file generated for hyperliquid-bot-v8
app = 'hyperliquid-bot-v8'
primary_region = 'cdg'

[build]

[env]
  DEBUG = 'true'

# Pas de http_service — c'est un worker, pas un web service

[processes]
  app = "python main.py"

[[restart]]
  policy = 'always'
  max_retries = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpus = 1
  memory_mb = 512
  auto_stop = false
  auto_start = true
